global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'careforall-services'
    static_configs:
      - targets: 
        - 'gateway:8080'
        - 'auth:3001'
        - 'campaign:3002'
        - 'pledge:3003'
        - 'payment:3004'
    metrics_path: '/metrics'
